replicaCount: 2

image:
  repository: <ECR_URL>
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

config:
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "*"
  DB_ENGINE: django.db.backends.sqlite3
  DB_NAME: /app/db.sqlite3

autoscaler:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
