replicaCount: 2

image:
  repository: <ECR_URL>
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

config:
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "*"
  POSTGRES_DB: vk-db
  POSTGRES_USER: vk
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"

autoscaler:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
