apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-django-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-django
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-django
    spec:
      containers:
        - name: django
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-django-config
