apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-django-service
spec:
  selector:
    app: {{ .Release.Name }}-django
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: {{ .Values.service.type }}
