apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Chart.Name }}
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: HEAD
    path: {{ .Values.path }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
