{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argo-cd
spec:
  project: {{ .project | default "default" }}
  source:
    repoURL: {{ .source.repoURL }}
    targetRevision: {{ .source.targetRevision | default "HEAD" }}
    {{- if .source.path }}
    path: {{ .source.path }}
    {{- end }}
    {{- if .source.chart }}
    chart: {{ .source.chart }}
    {{- end }}
    {{- if .source.helm }}
    helm:
      {{- if .source.helm.valueFiles }}
      valueFiles:
        {{- toYaml .source.helm.valueFiles | nindent 8 }}
      {{- end }}
      {{- if .source.helm.values }}
      values: |
        {{- .source.helm.values | nindent 8 }}
      {{- end }}
    {{- end }}
  destination:
    server: {{ .destination.server | default "https://kubernetes.default.svc" }}
    namespace: {{ .destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
