apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-server-proxy-patch
rules:
- apiGroups: [""]
  resources: ["nodes/proxy"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-server-proxy-patch-binding
subjects:
- kind: ServiceAccount
  name: prometheus-server
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: prometheus-server-proxy-patch
  apiGroup: rbac.authorization.k8s.io
