apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argo-cd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: {{ .Values.repoURL }}
  password: {{ .Values.password }}
  username: {{ .Values.username }}
